name: deploy_frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to blob storage
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az storage blob upload-batch --account-name azureresumesaeh --auth-mode key -d '$web' -s frontend/ --overwrite

      - name: Purge CDN endpoint
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az cdn endpoint purge --content-paths "/*" --profile-name "azureresumeeh" --name "azureresumeeh" --resource-group "azureresume-rg"

      - name: logout
        run: |
          az logout
        if: always()
